### ISSUE TITLE
something is wrong.....

### ISSUE THREAD

**Issue by smallmeet** [attackercan/burp-xss-sql-plugin#1]
NotImplementedError

	at org.python.core.Py.NotImplementedError(Py.java:167)
	at org.python.proxies.__main__$BurpExtender$6.processProxyMessage(Unknown Source)
	at burp.jvd.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by attackercan** [comment]
It works fine for me.
Tested on latest Burp and on Burp v1.7.11 with Jython 2.7.0
